# 基本设置
title: 祥安生命有限公司
description: 推薦禮儀公司，透明化價格，專業服務，傾聽訴求，由您來決定如何陪伴家人走完最後一程
url: "https://24hour.台灣" # 例如 https://24hour.台湾
baseurl: "" # 如果你没有使用子目录，可以留空

# 主题设置
theme: jekyll-theme-primer # 你使用的主题名称

# 站点作者信息
author:
  name: 陳姸如
  email: ava85110@yahoo.com.tw

# 社交媒体链接（可选）
social:
  facebook: https://www.facebook.com/shianganlife
  line: https://line.me/ti/p/TuM5y_Of6I

# 插件设置
plugins:
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-default-layout

# 生成内容的设置
paginate: 5 # 每页显示的文章数量
paginate_path: "/page:num/" # 分页的路径

# Permalink 设置
permalink: /:year/:month/:day/:title/ # 文章的链接格式

# 其他设置
markdown: kramdown # 选择 Markdown 解析器
kramdown:
  input: GFM # GitHub 风格的 Markdown
