name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'  # Specify the Ruby version your Jekyll site uses
        bundler-cache: true    # Enable caching for Bundler

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build the site
      run: |
        bundle exec jekyll build --future

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'  # Only deploy on push to main
      run: |
        # Example for deploying to GitHub Pages
        echo "Deploying to GitHub Pages..."
        # Add your deployment commands here, e.g., pushing to the gh-pages branch
